### ISSUE TITLE
[vagrant-vm] warning to solve

### ISSUE THREAD

**Issue by fgiacomoni** [workflow4metabolomics/w4m-vm#12]
During the vagrant up:
```
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default).
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

**Comment by pierrickrogermele** [comment]
This a warning issued when running the ansible-galaxy-tools role. The ansible-galaxy-tools is a repository part of the galaxy project. I'll try to update to latest version of this repos and see if the warning goes away.

**Comment by pierrickrogermele** [comment]
Oh ! there are also such warnings for our ansible provisioning files. I'll look at that.

**Comment by fgiacomoni** [comment]
Thanks Pierrick

**Comment by pierrickrogermele** [comment]
Ok, I've solved them on branch debug-vagrant.
I wait for merging into master, because the TravisCI build fails for that branch. I've asked Gildas for advise.
Please use branch debug-vagrant in the meantime.
