### ISSUE TITLE
[vagrant-vm] Tools outside sections

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/w4m-vm#14]
After a break in the testing of this solution, now, tools don't appear in the good sections in the tool panel.

A lot of layer have obviously be updated:
- Ansible python library
- Ansible-galaxy
- Ansible-galaxy-tools
- Galaxy itself
- Vagrant
- …

**Comment by bgruening** [comment]
Which Galaxy version is this using? We fixed this I think. But not sure where, maybe only in Galaxy dev :(

**Comment by fgiacomoni** [comment]
Hi, folks
working on it to find what's happening and... I found some points but not totally solve the issue
  * edit ~galaxy/config/tool_conf.xml with: <toolbox tool_path="tools/">
  * edit ~galaxy/config/shed_tool_conf.xml with: <toolbox tool_path="../shed_tools">
  * "section" tags are missing in shed_tool_conf.xml - they are not created during the installation step

**Comment by fgiacomoni** [comment]
Galaxy version is release_16.04

**Comment by lecorguille** [comment]
I had this with the Docker too.
Maybe, there isn't a good retrocompatibility from ansible ruled and "old"
Galaxy version.
Try to switch to 16.07 ! ?

**Comment by fgiacomoni** [comment]
Try to switch to 16.07... same results ! I found a release of the ansible-galaxy-tools github project... with a major feature: the use of ephemeris to get tools from the TS instead of files/install_tool_shed_tools.py (https://github.com/galaxyproject/ansible-galaxy-tools/commit/e871f0173390ce554e709d6d2d8098b2a494a720).

**Comment by bgruening** [comment]
@lecorguille it's more or less the same script which we just moved around. It can be reason, but I would think is unlikely, travis testing in Galaxy Docker stable was working at anytime during this migration.

**Comment by lecorguille** [comment]
@pierrickrogermele Is it solve?

**Comment by pierrickrogermele** [comment]
No, and I won't solve it. For the time being I will concentrate on building using GitHub code source, and placing the tools at the right place inside the `tool_conf.xml` with a script of mine.
