### ISSUE TITLE
travis issue on branch debug-vagrant

### ISSUE THREAD

**Issue by pierrickrogermele** [workflow4metabolomics/w4m-vm#16]
Don't know why Travis CI bugs when testing docker. It says:
         Cannot write to ‘master.tar.gz’ (Success).
Any idea Gildas ?

**Comment by lecorguille** [comment]
https://github.com/bgruening/galaxy-flavor-testing/issues/3

**Comment by lecorguille** [comment]
Fix and moreover move to w4m-docker.
You can remove the .travis.yml and the badge if you want.
