### ISSUE TITLE
Some good news for testing!

### ISSUE THREAD

**Issue by bgruening** [workflow4metabolomics/w4m-vm#17]
@lecorguille it took me a while but I finally fixed the long startup time of Docker containers.
The `:dev` branch should be able to be used for testing without reaching the travis max-build time and the travis storage limit. See this example here: https://github.com/bgruening/docker-galaxy-ngs-preprocessing/compare/dev?expand=1

Any testing is appreciated and hopefully this will become 16.10 soon.

**Comment by lecorguille** [comment]
Cool, I will test that ... ASAP 
But I'm afraid to still meet that issue https://github.com/galaxyproject/planemo/issues/604 So I can't update our Docker image until it is fixed

**Comment by lecorguille** [comment]
Yep, it's a really good step.

**Comment by pierrickrogermele** [comment]
Issue related to docker version. See new repos <https://github.com/workflow4metabolomics/w4m-docker>.

**Comment by lecorguille** [comment]
My new builds after a long break work.
So all good for me 👍
