### ISSUE TITLE
Suggestion: move docker code to dedicated repos

### ISSUE THREAD

**Issue by pierrickrogermele** [workflow4metabolomics/w4m-vm#18]
@lecorguille @cduperier 
I was wondering if it would not be better to split the code, and have a dedicated repos for docker (w4m-docker), for more visibility and ease of maintenance.
What do you think ?
Since the only thing in common is the list of tools, we could have either a repos dedicated to that (w4m-ansible) or a copy in each repos.

**Comment by lecorguille** [comment]
I don't know ... why not!?
There are also some config files and static stuff.

**Comment by pierrickrogermele** [comment]
The files in `files4galaxy`, right ? So maybe rather a submodule named `w4m-config` than `w4m-ansible` with all file from `files4galaxy` and the ansible scripts.
I would suggest we make a copy of `w4m-vm` into new repos `w4m-docker`, using `git push --mirror`. And then create `w4m-config`.
Let me know if you are ok with that.

**Comment by lecorguille** [comment]
OK

**Comment by pierrickrogermele** [comment]
`w4m-docker` and `w4m-config` are created.
Should I enable travis build for `w4m-docker` now or do you want to do it yourself later?
I'll let you do the cleaning in `w4m-docker`, getting rid of all vagrant stuff and using `w4m-config` as submodule. I'll deal with `w4m-vm`.

**Comment by lecorguille** [comment]
Deal!

**Comment by lecorguille** [comment]
@pierrickrogermele w4m-docker is not synchronize. A lot of commits are not there.

**Comment by pierrickrogermele** [comment]
Je viens de faire un clone, et j'obtiens exactement la même liste de commits. Peux-tu me donner une exemple de commit que tu ne retrouves pas ?

**Comment by lecorguille** [comment]
https://github.com/workflow4metabolomics/w4m-vm/commits/master
Le dernier commit date du 10 mars
https://github.com/workflow4metabolomics/w4m-docker/commits/master

**Comment by pierrickrogermele** [comment]
Ah. Il manque aussi une branche (conda_cleanup).
Je pense que c'est parce que mes branches locales ne sont pas synchro.
Je vais le refaire.

**Comment by pierrickrogermele** [comment]
C'est bon, j'ai supprimé et recréé le repos. Toutes les branches sont là et sont correctes maintenant.

**Comment by lecorguille** [comment]
Oki
Je me relance dans Docker.
