### ISSUE TITLE
Missing datatypes in VM

### ISSUE THREAD

**Issue by yguitton** [workflow4metabolomics/w4m-vm#30]
Hi,

While trying to use the new VM w4mprod_azerty_1 (build done by @fgiacomoni) i have the following error when launching xcms.xcmsSet on a zip folder (https://github.com/workflow4metabolomics/metaMS/blob/master/galaxy/metaMS/test-data/W4M_GCMS_Dataset.zip)

all default parameters--> execute

Fatal error: Exit code 1 ()
Error: package or namespace load failed for 'mzR' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/vagrant/galaxy/config/job_working_directory/000/25/conda-env/lib/R/library/mzR/libs/mzR.so':
  libnetcdf.so.11: cannot open shared object file: No such file or directory
Error: library(pkg, quietly = TRUE, logical.return = TRUE, character.only = TRUE) is not TRUE
Execution halted
WARNING:galaxy.model:Datatype class not found for extension 'rdata.xcms.raw'
WARNING:galaxy.model:Datatype class not found for extension 'rdata.xcms.raw'
WARNING:galaxy.model:Datatype class not found for extension 'rdata.xcms.raw'
WARNING:galaxy.model:Datatype class not found for extension 'rdata.xcms.raw'
WARNING:galaxy.model:Datatype class not found for extension 'rdata.xcms.raw'

I think that other datatypes are missing 
Help me
Yann

**Comment by pkrog** [comment]
Solved by upgrading to Galaxy 18.05.

**Comment by bernt-matthias** [comment]
Note that this are actually two problems: The first is a broken conda package (mzR:https://github.com/workflow4metabolomics/profia/pull/9 ) and the latter a Galaxy data type problem.

Don't understand how a Galaxy upgrade could have solved the first problem...

**Comment by pkrog** [comment]
I don't remember, but the error disappeared after upgrading.
When you have solved the mzR conda issue in tools, please let me know so I can upgrade the VM.
Next time, please, just open a new issue and make reference to the closed issue, otherwise I may forget to follow discussions on closed issue.
