### ISSUE TITLE
Build does *not* fail on mzR

### ISSUE THREAD

**Issue by sneumann** [workflow4metabolomics/w4m-vm#4]
Hi, in https://hub.docker.com/r/lecorguille/galaxy-workflow4metabolomics/builds/bex55xgwjaageqeuggt92sn/ 
I don't see a failure due to mzR (or it didn't reach that step yet ?!). There is ```` * The PostgreSQL server failed to start. Please check the log output:``` and galaxy fails with ````OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused````. 
We have a working bioconductor_metabolomics docker at http://phenomenal-h2020.eu/jenkins/job/bioc_docker_devel_metabolomics/11/ . Yours, Steffen

**Comment by lecorguille** [comment]
It is not more a problem since I use now conda dependencies I wrote in our new (this week) different VM (Vagrant and Docker)
http://bioconda.github.io/recipes/bioconductor-xcms/README.html
http://bioconda.github.io/recipes/bioconductor-camera/README.html
