### ISSUE TITLE
Postgres fails to start

### ISSUE THREAD

**Issue by sneumann** [workflow4metabolomics/w4m-vm#5]
Hi, related comments seem to be here:
https://github.com/nimiq/docker-postgresql93/issues/2
Yours, Steffen

**Comment by lecorguille** [comment]
You can test again with this new version of the Docker container.
It is based on a new version of the Galaxy Docker.

**Comment by pierrickrogermele** [comment]
Docker related issue. See new repos <https://github.com/workflow4metabolomics/w4m-docker>.
